services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data16:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:v1.11.3
    ports:
      - 127.0.0.1:6333:6333 
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    environment:
      - QDRANT_HOST=0.0.0.0
  
  web:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST:-localhost}
      DJNAGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME:-chatbot}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_HOST: ${DATABASE_HOST:-db}
    command: bash -c 'python manage.py runserver 0.0.0.0:8100'
    volumes:
      - .:/code
    ports:
      - 127.0.0.1:8001:8001 

    depends_on:
      - db
      - redis
      - qdrant


volumes:
  postgres-data16:
  redis-data:
  qdrant_data:
