services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data16:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:v1.11.3
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    environment:
        # https://qdrant.tech/documentation/guides/configuration/#environment-variables
        # https://github.com/qdrant/qdrant/blob/master/config/config.yaml
        QDRANT__SERVICE__HOST: 0.0.0.0
        QDRANT__SERVICE__HTTP_PORT: 6333
  
  web:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DJNAGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      QDRANT_DB_HOST: ${QDRANT_DB_HOST:-0.0.0.0}
      QDRANT_DB_PORT: ${QDRANT_DB_PORT:-6333}
      QDRANT_DB_COLLECTION_NAME: ${QDRANT_DB_COLLECTION_NAME:-test}
      EMBEDDING_MODEL_URL: ${EMBEDDING_MODEL_URL:-localhost}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-embedding_model}
      EMBEDDING_MODEL_VECTOR_SIZE: ${EMBEDDING_MODEL_VECTOR_SIZE:-384}
      EMBEDDING_MODEL_TYPE: ${EMBEDDING_MODEL_TYPE:-1}
      OLLAMA_EMBEDDING_MODEL_BASE_URL: ${OLLAMA_EMBEDDING_MODEL_BASE_URL:-model}
      LLM_TYPE: ${LLM_TYPE:-1}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME:-"mistral:latest"}
      LLM_OLLAMA_BASE_URL: ${LLM_OLLAMA_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
    command: bash -c 'python manage.py runserver 0.0.0.0:8001'
    volumes:
      - .:/code
    ports:
      - 8001:8001 

    depends_on:
      - db
      - redis
      - qdrant

  worker:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST:-localhost}
      DJNAGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME:-chatbot}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      QDRANT_DB_HOST: ${QDRANT_DB_HOST:-0.0.0.0}
      QDRANT_DB_PORT: ${QDRANT_DB_PORT:-6333}
      QDRANT_DB_COLLECTION_NAME: ${QDRANT_DB_COLLECTION_NAME:-test}
      EMBEDDING_MODEL_URL: ${EMBEDDING_MODEL_URL:-localhost}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-embedding_model}
      EMBEDDING_MODEL_VECTOR_SIZE: ${EMBEDDING_MODEL_VECTOR_SIZE:-384}
      EMBEDDING_MODEL_TYPE: ${EMBEDDING_MODEL_TYPE:-1}
      OLLAMA_EMBEDDING_MODEL_BASE_URL: ${OLLAMA_EMBEDDING_MODEL_BASE_URL:-model}
      LLM_TYPE: ${LLM_TYPE:-1}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME:-"mistral:latest"}
      LLM_OLLAMA_BASE_URL: ${LLM_OLLAMA_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}

    command: celery -A main worker --loglevel=info
    depends_on:
      - redis
      - web
  

volumes:
  postgres-data16:
  redis-data:
  qdrant_data:
