services:
  web:
    image: $DOCKER_IMAGE_BACKEND
    env_file: !reset null
    environment:
      CI: "true"
      DJANGO_SECRET_KEY: "test"
      LLM_OLLAMA_BASE_URL: "http://localhost:8000"
      APP_ENVIRONMENT: CI
      APP_TYPE: web

    volumes:
      - ./coverage/:/code/coverage/

