# Generated by Django 5.1.6 on 2025-04-17 03:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('user', 'organization')},
        ),
    ]
