"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=str,
    DJANGO_CORS_ORIGIN_REGEX_WHITELIST=(list, []),
    DJANGO_ALLOWED_HOST=(list, ["*"]),
    DJANGO_TIME_ZONE=(str, "UTC"),
    APP_HTTP_PROTOCOL=str,
    APP_ENVIRONMENT=str,
    APP_DOMAIN=str,
    APP_FRONTEND_HOST=str,
    # Storage
    DJANGO_STATIC_ROOT=(str, os.path.join(BASE_DIR, "assets/static")),  # Where to store
    DJANGO_MEDIA_ROOT=(str, os.path.join(BASE_DIR, "assets/media")),  # Where to store
    DJANGO_STATIC_URL=(str, "/static/"),
    DJANGO_MEDIA_URL=(str, "/media/"),
    # -- S3
    USE_S3_BUCKET=(bool, False),
    AWS_S3_AWS_ENDPOINT_URL=str,
    AWS_S3_ACCESS_KEY_ID=str,
    AWS_S3_SECRET_ACCESS_KEY=str,
    AWS_S3_REGION=str,
    S3_STATIC_BUCKET_NAME=str,
    S3_MEDIA_BUCKET_NAME=str,
    # Database
    DATABASE_NAME=str,
    DATABASE_USER=str,
    DATABASE_PASSWORD=str,
    DATABASE_HOST=str,
    DATABASE_PORT=int,
    # Redis
    CELERY_REDIS_URL=str,
    DJANGO_CACHE_REDIS_URL=str,
    # -- For running test (Optional)
    SENTRY_DSN=(str, None),
    SENTRY_TRACES_SAMPLE_RATE=(float, 0.2),
    SENTRY_PROFILE_SAMPLE_RATE=(float, 0.2),
    # App Domain
    # Vector Database
    QDRANT_DB_HOST=str,
    QDRANT_DB_PORT=int,
    QDRANT_DB_COLLECTION_NAME=str,
    # Embedding Model
    EMBEDDING_MODEL_URL=str,
    EMBEDDING_MODEL_NAME=str,
    EMBEDDING_MODEL_VECTOR_SIZE=int,
    EMBEDDING_MODEL_TYPE=int,
    OLLAMA_EMBEDDING_MODEL_BASE_URL=(str, None),
    # LLM Type
    LLM_TYPE=int,
    LLM_MODEL_NAME=str,
    LLM_OLLAMA_BASE_URL=(str, None),
    # OpenAI API key
    OPENAI_API_KEY=(str, None),
    # Celery
    CELERY_BROKER_URL=str,
    CELERY_RESULT_BACKEND=str,
    CELERY_ACCEPT_CONTENT=(list, ["json"]),
    CELERY_TASK_SERIALIZER=(str, "json"),
    CELERY_RESULT_SERIALIZER=(str, "json"),
    CELERY_TIMEZONE=(str, "UTC"),
    # Email
    EMAIL_BACKEND=str,
    # -- SMTP
    EMAIL_HOST=str,
    EMAIL_USE_SSL=(bool, False),
    EMAIL_PORT=int,
    EMAIL_HOST_USER=str,
    EMAIL_HOST_PASSWORD=str,
    DEFAULT_FROM_EMAIL=str,
)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOST")

APP_HTTP_PROTOCOL = env("APP_HTTP_PROTOCOL")
APP_ENVIRONMENT = env("APP_ENVIRONMENT")
APP_DOMAIN = env("APP_DOMAIN")

SESSION_COOKIE_NAME = f"aichatbot-{APP_ENVIRONMENT}-sessionid"
if APP_HTTP_PROTOCOL == "https":
    SESSION_COOKIE_NAME = f"__Secure-{SESSION_COOKIE_NAME}"
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = 30  # TODO: Increase this slowly
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = [
        f"{APP_HTTP_PROTOCOL}://{APP_DOMAIN}",
    ]
# Note: The embedding model and vector size both should be compatible
# and chosen carefully
# If the embedding model is changed, we need to re-vectorize all the
# texts in the vector database

# Embedding Model selection
EMBEDDING_MODEL_TYPE = env("EMBEDDING_MODEL_TYPE")
EMBEDDING_MODEL_URL = env("EMBEDDING_MODEL_URL")
EMBEDDING_MODEL_NAME = env("EMBEDDING_MODEL_NAME")
EMBEDDING_MODEL_VECTOR_SIZE = env("EMBEDDING_MODEL_VECTOR_SIZE")
OLLAMA_EMBEDDING_MODEL_BASE_URL = env("OLLAMA_EMBEDDING_MODEL_BASE_URL")
# LLM selection
LLM_TYPE = env("LLM_TYPE")
LLM_MODEL_NAME = env("LLM_MODEL_NAME")
LLM_OLLAMA_BASE_URL = env("LLM_OLLAMA_BASE_URL")
# Qdrant database
QDRANT_DB_HOST = env("QDRANT_DB_HOST")
QDRANT_DB_PORT = env("QDRANT_DB_PORT")
QDRANT_DB_COLLECTION_NAME = env("QDRANT_DB_COLLECTION_NAME")
# OPENAI API KEY
OPENAI_API_KEY = env("OPENAI_API_KEY")

if EMBEDDING_MODEL_TYPE == 2 and not OLLAMA_EMBEDDING_MODEL_BASE_URL:
    raise ValueError("Ollama base url is not set.")

if (EMBEDDING_MODEL_TYPE == 3 and LLM_TYPE == 1) and not OPENAI_API_KEY:
    raise ValueError("OpenAI API key is not set.")

if LLM_TYPE == 2 and not LLM_OLLAMA_BASE_URL:
    raise ValueError("Ollama base url is not set.")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "user",
    "common",
    "content",
    "organization",
    "rest_framework",
    "corsheaders",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS
if not env("DJANGO_CORS_ORIGIN_REGEX_WHITELIST"):
    CORS_ORIGIN_ALLOW_ALL = True
else:
    # Example ^https://[\w-]+\.mapswipe\.org$
    CORS_ORIGIN_REGEX_WHITELIST = env("DJANGO_CORS_ORIGIN_REGEX_WHITELIST")

CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r"(^/media/.*$)|(^/graphql/$)"
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "sentry-trace",
)


# Strawberry
# -- Pagination
STRAWBERRY_ENUM_TO_STRAWBERRY_ENUM_MAP = "main.graphql.enums.ENUM_TO_STRAWBERRY_ENUM_MAP"
STRAWBERRY_DEFAULT_PAGINATION_LIMIT = 50
STRAWBERRY_MAX_PAGINATION_LIMIT = 100

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "OPTIONS": {"options": "-c search_path=public"},
    },
}

AUTH_USER_MODEL = "user.User"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("DJANGO_TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = env("CELERY_ACCEPT_CONTENT")
CELERY_TASK_SERIALIZER = env("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = env("CELERY_RESULT_SERIALIZER")
CELERY_TIMEZONE = env("CELERY_TIMEZONE")


STATIC_URL = env("DJANGO_STATIC_URL")
MEDIA_URL = env("DJANGO_MEDIA_URL")

# Django storage
if env("USE_S3_BUCKET"):
    AWS_S3_ENDPOINT_URL = env("AWS_S3_AWS_ENDPOINT_URL")

    AWS_S3_ACCESS_KEY_ID = env("AWS_S3_ACCESS_KEY_ID")
    AWS_S3_SECRET_ACCESS_KEY = env("AWS_S3_SECRET_ACCESS_KEY")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION")

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": env("S3_MEDIA_BUCKET_NAME"),
                "location": "media/",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": env("S3_STATIC_BUCKET_NAME"),
                "location": "static/",
            },
        },
    }

else:
    STATIC_ROOT = env("DJANGO_STATIC_ROOT")
    MEDIA_ROOT = env("DJANGO_MEDIA_ROOT")

APP_FRONTEND_HOST = env("APP_FRONTEND_HOST")
# Email
EMAIL_FROM = env("DEFAULT_FROM_EMAIL")
SPECIFIED_EMAIL_BACKEND = env("EMAIL_BACKEND").upper()

if SPECIFIED_EMAIL_BACKEND == "SMTP":
    # Configure SMTP backend settings
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST")
    EMAIL_PORT = env("EMAIL_PORT")
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    EMAIL_USE_SSL = env("EMAIL_USE_SSL")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
