{{- if .Values.app.embeddingModel.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "tc-chatbot-backend.fullname" . }}-embedding-model-pvc
  labels:
    component: embedding-model-deployment
    environment: {{ .Values.app.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.app.embeddingModel.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.app.embeddingModel.persistence.size }}

{{- end }}
