{{- if .Values.app.embeddingModel.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "tc-chatbot-backend.fullname" . }}-embedding-model-svc
  labels:
    app: {{ template "tc-chatbot-backend.name" . }}
    component: embedding-model-service
    environment: {{ .Values.app.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "tc-chatbot-backend.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-embedding-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.embeddingModel.containerPort }}
      nodePort: null

{{- end }}
