from django.db import models

# Create your models here.


class UserChatSession(models.Model):
    class Platform(models.IntegerChoices):
        WHATSAPP = 0, "Whatsapp"
        FACEBOOK = 1, "Facebook"
        STREAMLIT = 2, "Streamlit"
        WEBSITE = 3, "Website"
        AUTOMATION = 4, "Automation"  # Used for QA team

    user_uuid = models.UUIDField()  # TODO We need to retrieve the user ID from the user model. Currently, we are using a UUID generated by Streamlit.
    created_at = models.DateTimeField(auto_now_add=True)
    platform = models.IntegerField(choices=Platform.choices, default=Platform.STREAMLIT)

    def __str__(self):
        return str(self.user_uuid)


class UserChatMessage(models.Model):
    class MessageType(models.IntegerChoices):
        BOT = 0, "Bot"
        USER = 1, "User"

    class Status(models.IntegerChoices):
        PENDING = 0, 'Pending'
        STARTED = 1, 'Started'
        SUCCESS = 2, 'Success'
        FAILED = 3, 'Failed'

    session = models.ForeignKey(UserChatSession, on_delete=models.CASCADE)
    type = models.IntegerField(choices=MessageType.choices, default=MessageType.USER)
    question = models.TextField()
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)
    answer = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
