kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "tc-chatbot-backend.fullname" . }}-api-configmap
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  APP_ENVIRONMENT: {{ .Values.environment | upper | quote }}
  APP_DOMAIN: {{ required "env.APP_DOMAIN" .Values.environment | upper | quote }}
  DJANGO_TIME_ZONE: {{ .Values.env.DJANGO_TIME_ZONE }}
  DJANGO_DEBUG: {{ .Values.env.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOST: {{ .Values.env.DJANGO_ALLOWED_HOST | quote }}
  APP_HTTP_PROTOCOL: {{ .Values.env.APP_HTTP_PROTOCOL | quote }}

  {{- if .Values.redis.enabled }}
  # Redis
  DJANGO_CACHE_REDIS_URL: "redis://{{ template "tc-chatbot-backend.fullname" . }}-redis:6379/1"
  # -- Celery
  CELERY_REDIS_URL: "redis://{{ template "tc-chatbot-backend.fullname" . }}-redis:6379/0"
  CELERY_BROKER_URL: "redis://{{ template "tc-chatbot-backend.fullname" . }}-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://{{ template "tc-chatbot-backend.fullname" . }}-redis:6379/0"
  {{- else }}
  CELERY_REDIS_URL: {{ required "env.CELERY_REDIS_URL" .Values.env.CELERY_REDIS_URL | quote }}
  CACHE_REDIS_URL: {{ required "env.CACHE_REDIS_URL" .Values.env.CACHE_REDIS_URL | quote }}
  {{- end }}

  # Sentry
  SENTRY_TRACES_SAMPLE_RATE: {{ .Values.env.SENTRY_TRACES_SAMPLE_RATE | quote }}
  SENTRY_PROFILE_SAMPLE_RATE: {{ .Values.env.SENTRY_PROFILE_SAMPLE_RATE | quote }}
  # App Domain
  # Vector Database
  QDRANT_DB_HOST: {{ .Values.env.QDRANT_DB_HOST | quote }}
  QDRANT_DB_PORT: {{ .Values.env.QDRANT_DB_PORT | quote }}
  QDRANT_DB_COLLECTION_NAME: {{ .Values.env.QDRANT_DB_COLLECTION_NAME | quote }}
  # Embedding Model
  EMBEDDING_MODEL_URL: {{ .Values.env.EMBEDDING_MODEL_URL | quote }}
  EMBEDDING_MODEL_NAME: {{ .Values.env.EMBEDDING_MODEL_NAME | quote }}
  EMBEDDING_MODEL_VECTOR_SIZE: {{ .Values.env.EMBEDDING_MODEL_VECTOR_SIZE | quote }}
  EMBEDDING_MODEL_TYPE: {{ .Values.env.EMBEDDING_MODEL_TYPE | quote }}
  OLLAMA_EMBEDDING_MODEL_BASE_URL: {{ .Values.env.OLLAMA_EMBEDDING_MODEL_BASE_URL | quote }}
  # LLM Type
  LLM_TYPE: {{ .Values.env.LLM_TYPE | quote }}
  LLM_MODEL_NAME: {{ .Values.env.LLM_MODEL_NAME | quote }}
  LLM_OLLAMA_BASE_URL: {{ .Values.env.LLM_OLLAMA_BASE_URL | quote }}
