kind: Secret
apiVersion: v1
metadata:
  name: {{ template "tc-chatbot-backend.fullname" . }}-api-secret
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}

  # Database
  {{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  DATABASE_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
  DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DATABASE_NAME: {{ .Values.postgresql.auth.database | quote }}
  {{- else }}
  DATABASE_NAME: {{ required "secrets.DATABASE_NAME" .Values.secrets.DATABASE_NAME | quote }}
  DATABASE_USER: {{ required "secrets.DATABASE_USER" .Values.secrets.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ required "secrets.DATABASE_PASSWORD" .Values.secrets.DATABASE_PASSWORD | quote }}
  DATABASE_HOST: {{ required "secrets.DATABASE_HOST" .Values.secrets.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ required "secrets.DATABASE_PORT" .Values.secrets.DATABASE_PORT | quote }}
  {{- end }}

  # Sentry
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN }}
  # OpenAI
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY }}

  # S3
  {{- if .Values.env.USE_S3_BUCKET }}
  AWS_S3_ACCESS_KEY_ID: {{ required ".secrets.AWS_S3_ACCESS_KEY_ID" .Values.secrets.AWS_S3_ACCESS_KEY_ID | quote }}
  AWS_S3_SECRET_ACCESS_KEY: {{ required "secrets.AWS_S3_SECRET_ACCESS_KEY" .Values.secrets.AWS_S3_SECRET_ACCESS_KEY | quote }}
  {{- end }}
