# Generated by Django 5.1.4 on 2025-01-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userchatmessage",
            old_name="question",
            new_name="query",
        ),
        migrations.RenameField(
            model_name="userchatmessage",
            old_name="answer",
            new_name="response",
        ),
    ]
