{{- if .Values.argoHooks.enableDatabaseMigration }}

apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ template "tc-chatbot-backend.fullname" . }}-database-migration-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-db-migrate
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./manage.py"
            - "migrate"
      restartPolicy: Never

{{- end }}
