{{- range $hookName, $hook := .Values.argoHooks }}

{{- if $hook.enabled }}

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ template "tc-chatbot-backend.fullname" $ }}-{{ $hookName }}-
  annotations:
    argocd.argoproj.io/hook: {{ $hook.hook }}
spec:
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/config/secret.yaml") $ | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/config/configmap.yaml") $ | sha256sum }}
    spec:
      restartPolicy: "Never"
      containers:
        - name: {{ $.Chart.Name }}-{{ $hookName }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
              {{- range $hook.command }}
              - "{{ . }}"
              {{- end }}
          resources:
            requests:
              cpu: {{ default $.Values.api.resources.requests.cpu $hook.requestsCpu }}
              memory: {{ default $.Values.api.resources.requests.memory $hook.requestsMemory }}
            limits:
              cpu: {{ default $.Values.api.resources.limits.cpu $hook.limitsCpu }}
              memory: {{ default $.Values.api.resources.limits.memory $hook.limitsMemory }}
          envFrom:
            - secretRef:
                name: {{ template "tc-chatbot-backend.fullname" $ }}-api-secret
            - configMapRef:
                name: {{ template "tc-chatbot-backend.fullname" $ }}-api-configmap

{{- end }}

{{- end }}
