# Generated by Django 5.1.6 on 2025-05-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
