environment: prod

image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG
  imagePullPolicy: IfNotPresent

ingress:
  className: nginx
  api:
    enabled: false
    host:
  streamlit:
    enabled: false
    host:

postgresql:
  enabled: true
  architecture: standalone
  auth:
    database: chatbot
    # NOTE: For production. Use existingSecret.
    # TODO: Pass existingSecret to api/worker instances
    username: chatbot
    password: chatbot
  primary:
    resourcesPreset: "nano"
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "longhorn"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    resourcesPreset: "nano"
    persistence:
      enabled: true
      size: .5Gi
      storageClass: "longhorn"

qdrant:
  enabled: true
  persistence:
    storageClassName: "longhorn"
    accessModes:
      - "ReadWriteOnce"
    size: 2Gi
  resources:
    requests:
      cpu: "100m"
      memory: 100Mi
    limits:
      cpu: "100m"
      memory: 200Mi

# TODO: persistence for uploaded files
api:
  enabled: true
  replicaCount: 1
  containerPort: 80
  resources:
    requests:
      cpu: "200m"
      memory: 1Gi
    limits:
      cpu: "2000m"
      memory: 2Gi

worker:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: "200m"
      memory: 1.5Gi
    limits:
      cpu: "2"
      memory: 2Gi

streamlit:
  enabled: true
  image:
    name: ghcr.io/toggle-corp/expt-streamlit-chatapp
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 8501
  resources:
    requests:
      cpu: "200m"
      memory: 0.5Gi
    limits:
      cpu: "2"
      memory: 1Gi

embeddingModel:
  enabled: true
  image:
    name: ghcr.io/toggle-corp/embedding-models
    tag: latest
    pullPolicy: IfNotPresent
  persistence:  # Used to preserve downloaded models
    storageClassName: ""
    size: "30G"
  replicaCount: 1
  containerPort: 8000
  resources:
    requests:
      cpu: "200m"
      memory: 0.5Gi
    limits:
      cpu: "2"
      memory: 1Gi

env:
  # APP_ENVIRONMENT:
  DJANGO_DEBUG: false
  DJANGO_TIME_ZONE: UTC
  DJANGO_ALLOWED_HOST: "*"
  APP_HTTP_PROTOCOL: https
  APP_DOMAIN:
  # Redis (Required if redis.enabled is false)
  CELERY_REDIS_URL:
  DJANGO_CACHE_REDIS_URL:
  # -- Celery
  CELERY_BROKER_URL:
  CELERY_RESULT_BACKEND:
  # Sentry
  SENTRY_TRACES_SAMPLE_RATE: 0.2
  SENTRY_PROFILE_SAMPLE_RATE: 0.2
  # App Domain
  # Vector Database
  # QDRANT_DB_HOST: (Required if qdrant.enabled is false)
  QDRANT_DB_PORT: 6333
  QDRANT_DB_COLLECTION_NAME:
  # Embedding Model
  EMBEDDING_MODEL_URL:
  EMBEDDING_MODEL_NAME:
  EMBEDDING_MODEL_VECTOR_SIZE: 768
  EMBEDDING_MODEL_TYPE: 1
  OLLAMA_EMBEDDING_MODEL_BASE_URL:
  # LLM Type
  LLM_TYPE: 1
  LLM_MODEL_NAME:
  LLM_OLLAMA_BASE_URL:

secrets:
  DJANGO_SECRET_KEY:
  # Database (required if postgresql.enabled if false)
  DATABASE_NAME:
  DATABASE_USER:
  DATABASE_PASSWORD:
  DATABASE_HOST:
  DATABASE_PORT: 5432
  # Sentry
  SENTRY_DSN:
  # OpenAI API key
  OPENAI_API_KEY:
