# Generated by Django 5.1.1 on 2024-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_deleted_at_alter_content_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Text extracted'), (3, 'Added to vector'), (4, 'Deleted from vector'), (5, 'Failure')], default=1),
        ),
    ]
