# Generated by Django 5.1.6 on 2025-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='document_type',
            field=models.IntegerField(choices=[(1, 'WEB_URl'), (2, 'PDF'), (3, 'Text')], default=3),
        ),
    ]
