# Generated by Django 5.1.1 on 2024-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
