# Generated by Django 5.1.6 on 2025-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document_type',
            field=models.IntegerField(choices=[(1, 'WEB_URl'), (2, 'PDF'), (3, 'Text')], default=3),
        ),
    ]
