name: Builds and pushes Docker Images and Helm charts to Github Registry

on:
  push:
    branches:
      - develop
      - feature/tc-local-helm # TODO: Remove this

permissions:
  packages: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      push_docker_image: true

  build:
    name: Publish Helm
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Tag docker image in Helm Chart values.yaml
      env:
        IMAGE_NAME: ${{ needs.ci.outputs.docker_image_name }}
        IMAGE_TAG: ${{ needs.ci.outputs.docker_image_tag }}
      run: |
        # Update values.yaml with latest docker image
        sed -i "s|SET-BY-CICD-IMAGE|$IMAGE_NAME|" helm/values.yaml
        sed -i "s/SET-BY-CICD-TAG/$IMAGE_TAG/" helm/values.yaml

    - name: Package Helm Chart
      id: set-variables
      run: |
        SHA_SHORT=$(git rev-parse --short HEAD)
        sed -i "s/SET-BY-CICD/$SHA_SHORT/g" helm/Chart.yaml
        helm package ./helm -d .helm-charts

    - name: Push Helm Chart
      run: |
        PACKAGE_FILE=$(ls .helm-charts/*.tgz | head -n 1)
        helm push "$PACKAGE_FILE" oci://ghcr.io/${{ github.repository }}
